name: test

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:

jobs:
  integration:
    name: Integration tests
    strategy:
      matrix:
        platform: [macos-10.15, macos-11]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Show host info
        run: |
          uname -a
          sw_vers
          ifconfig
      - name: Install build dependencies of VDE
        run: brew install autoconf automake
      - name: Install VDE
        run: |
          git clone https://github.com/virtualsquare/vde-2.git /tmp/vde-2
          cd /tmp/vde-2
          # Dec 12, 2021
          git checkout 74278b9b7cf816f0356181f387012fdeb6d65b52
          autoreconf -fis
          ./configure --prefix=/opt/vde
          make
          sudo make install
      - name: Make
        run: make PREFIX=/opt/vde
      - name: Install
        run: sudo make PREFIX=/opt/vde install
      - name: Print launchd status (shared mode)
        run: launchctl print system/io.github.lima-vm.vde_vmnet.plist
      - name: Install test dependencies
        run: brew install qemu bash coreutils
      - name: Test (shared mode)
        run: ./test/test.sh /var/run/vde.ctl
# Bridged mode cannot be tested on GHA
